version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports: ["5432:5432"]
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports: ["6379:6379"]

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.16.0
    command: mlflow server --host 0.0.0.0 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlruns
    ports: ["5000:5000"]
    volumes:
      - mlruns:/mlruns

  backend:
    build: ./backend
    env_file: .env
    depends_on: [postgres, redis]
    ports: ["8080:8080"]
    volumes:
      - ./backend:/app
      - ./data:/data   # local persistence for FAISS, uploads, etc.

  frontend:
    build: ./frontend
    environment:
      - NEXT_PUBLIC_API=http://localhost:8080
    depends_on: [backend]
    ports: ["3000:3000"]
    volumes:
      - ./frontend:/usr/src/app

volumes:
  pg_data:
  mlruns:
